# Copyright (c) 2022 Arm Limited.
# SPDX-License-Identifier: Apache-2.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: [--max-line-length=88]

-   repo: local
    hooks:
    -   id: speclint
        name: speclint
        entry: python3 tools/speclint.py
        files: "tosa.xml"
        args: ["--xml"]
        language: python
