//
// This confidential and proprietary software may be used only as
// authorised by a licensing agreement from ARM Limited
// (C) COPYRIGHT 2020-2024 ARM Limited
// ALL RIGHTS RESERVED
// The entire notice above must be reproduced on all authorised
// copies and copies may only be made to the extent permitted
// by a licensing agreement from ARM Limited.

=== Comparison Operators

==== EQUAL

Elementwise comparison operation

*Precision Requirements*

Integer results must be exact.

The following rules apply to floating-point inputs:

* Comparison rules:
** The sign of a zero is ignored.
** Infinities of the same sign compare as equal.
** If either or both input values are a NaN, the result is false.
* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.

include::{generated}/operators/EQUAL.adoc[]

[source,c++]
----
include::{pseudocode}/operators/EQUAL.tosac[lines=10..-1]
----

==== GREATER

Elementwise greater than comparison operation

*Precision Requirements*

Integer results must be exact.

The following rules apply to floating-point inputs:

* Comparison rules:
** The sign of a zero is ignored.
** Infinities of the same sign compare as equal.
** If either or both input values are a NaN, the result is false.
* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.

include::{generated}/operators/GREATER.adoc[]

[source,c++]
----
include::{pseudocode}/operators/GREATER.tosac[lines=10..-1]
----

==== GREATER_EQUAL

Elementwise comparison operation

*Precision Requirements*

Integer results must be exact.

The following rules apply to floating-point inputs:

* Comparison rules:
** The sign of a zero is ignored.
** Infinities of the same sign compare as equal.
** If either or both input values are a NaN, the result is false.
* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.

include::{generated}/operators/GREATER_EQUAL.adoc[]

[source,c++]
----
include::{pseudocode}/operators/GREATER_EQUAL.tosac[lines=10..-1]
----
