//
// This confidential and proprietary software may be used only as
// authorised by a licensing agreement from ARM Limited
// (C) COPYRIGHT 2020,2023 ARM Limited
// ALL RIGHTS RESERVED
// The entire notice above must be reproduced on all authorised
// copies and copies may only be made to the extent permitted
// by a licensing agreement from ARM Limited.

=== Custom Operators

Hardware implementing TOSA may choose to add additional custom operators that are not expressed in the existing TOSA operations. These operators are not expected to be portable across TOSA implementations. The input and output signatures must be expressed in the corresponding TOSA node.

==== CUSTOM

Runs an implementation defined custom operator.
CUSTOM operators are not tested in the conformance suite as results will be implementation defined.
The `domain_name` attribute should be unique to each implementation.
To achieve this, using a domain name as the `domain_name` attribute is recommended.
No conformance testing is done for CUSTOM operators as they are implementation dependent.

include::{generated}/operators/CUSTOM.adoc[]

[source,c++]
----
include::{pseudocode}/operators/CUSTOM.tosac[lines=10..-1]
----
