//
// This confidential and proprietary software may be used only as
// authorised by a licensing agreement from ARM Limited
// (C) COPYRIGHT 2020-2024 ARM Limited
// ALL RIGHTS RESERVED
// The entire notice above must be reproduced on all authorised
// copies and copies may only be made to the extent permitted
// by a licensing agreement from ARM Limited.

=== Elementwise Unary Operators

==== ABS

Elementwise absolute value operation.

*Precision Requirements*

For floating-point values, in addition to the Floating-point behavior table, the following rules apply:

* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.
* Otherwise floating-point results must be exact.

include::{generated}/operators/ABS.adoc[]

*Floating-point behavior:*
|===
|Input|-infinity|+infinity|-0|+0|NaN

|Output|+infinity|+infinity|+0|+0|NaN
|===

[source,c++]
----
include::{pseudocode}/operators/ABS.tosac[lines=10..-1]
----

==== BITWISE_NOT

Elementwise bitwise NOT of input tensor.

*Precision Requirements*

Results must be exact.

include::{generated}/operators/BITWISE_NOT.adoc[]

[source,c++]
----
include::{pseudocode}/operators/BITWISE_NOT.tosac[lines=10..-1]
----

==== CEIL

Elementwise ceiling operation

*Precision Requirements*

* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.
* Infinity, NaN, and Zero behavior as defined in the following table.
* The following may be used to validate the result:
** Let `x` be an input element and `out_imp` the implementation output.
** Let `out_ref` be the result of the fp64_t reference implementation.
** Then `tosa_reference_check_fp<in_t>(out_imp, out_ref, 0.5)` must be true.

include::{generated}/operators/CEIL.adoc[]

*Floating-point behavior:*
|===
|Input|-infinity|+infinity|-0|+0|NaN

|Output|-infinity|+infinity|-0|+0|any NaN
|===

[source,c++]
----
include::{pseudocode}/operators/CEIL.tosac[lines=10..-1]
----

==== CLZ

Elementwise count leading zeros operation

*Precision Requirements*

Results must be exact.

include::{generated}/operators/CLZ.adoc[]

[source,c++]
----
include::{pseudocode}/operators/CLZ.tosac[lines=10..-1]
----

==== COS

Elementwise cosine operation for values given in radians.

*Precision Requirements*

* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.
* Infinity, NaN, and Zero behavior as defined in the following table.
* The following may be used to validate the result:
** Let `x` be an input element and `out_imp` the implementation output of `cos(x)`.
** Let `out_ref` be the result of the fp64_t reference implementation of `cos(x)`.
** Let `err_bnd = calcAbsErrorBound<in_out_t>(1+abs(x), 1, 0, 2)`.
** Then `tosa_reference_check_fp_bnd<in_out_t>(out_imp, out_ref, err_bnd)` must be true.

include::{generated}/operators/COS.adoc[]

*Floating-point behavior:*
|===
|Input|-infinity|+infinity|-0|+0|NaN

|Output|any NaN|any NaN|+1|+1|any NaN
|===

[source, c++]
----
include::{pseudocode}/operators/COS.tosac[lines=10..-1]
----

==== EXP

Elementwise e to the x operation

*Precision Requirements*

* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.
* Infinity, NaN, and Zero behavior as defined in the following table.
* The following may be used to validate the result:
** Let `x` be an input element and `out_imp` the implementation output of `exp(x)`.
** Let `out_ref` be the result of the fp64_t reference implementation of `exp(x)`.
** Let `err_bnd = calcAbsErrorBound<in_out_t>(out_ref, (1+abs(x)), 0, 1)`.
** Then `tosa_reference_check_fp_bnd<in_out_t>(out_imp, out_ref, err_bnd)` must be true.

include::{generated}/operators/EXP.adoc[]

*Floating-point behavior:*
|===
|Input|-infinity|+infinity|-0|+0|NaN

|Output|+0|+infinity|1|1|any NaN
|===

[source,c++]
----
include::{pseudocode}/operators/EXP.tosac[lines=10..-1]
----

==== FLOOR

Elementwise floor operation.

*Precision Requirements*

* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.
* Infinity, NaN, and Zero behavior as defined in the following table.
* The following may be used to validate the result:
** Let `x` be an input element and `out_imp` the implementation output.
** Let `out_ref` be the result of the fp64_t reference implementation.
** Then `tosa_reference_check_fp<in_t>(out_imp, out_ref, 0.5)` must be true.

include::{generated}/operators/FLOOR.adoc[]

*Floating-point behavior:*
|===
|Input|-infinity|+infinity|-0|+0|NaN

|Output|-infinity|+infinity|-0|+0|any NaN
|===

[source,c++]
----
include::{pseudocode}/operators/FLOOR.tosac[lines=10..-1]
----

==== LOG

Elementwise natural logarithm operation

*Precision Requirements*

* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.
* Infinity, NaN, and Zero behavior as defined in the following table.
* If the input to LOG is less than zero, then the result must be a NaN.
* The following may be used to validate the result:
** Let `x` be an input element and `out_imp` the implementation output.
** Let `out_ref` be the result of the fp64_t reference implementation.
** Then `tosa_reference_check_fp<in_t>(out_imp, out_ref, 5)` must be true.

include::{generated}/operators/LOG.adoc[]

*Floating-point behavior:*
|===
|Input|-infinity|+infinity|-0|+0|NaN

|Output|any NaN|+infinity|-infinity|-infinity|any NaN
|===

[source,c++]
----
include::{pseudocode}/operators/LOG.tosac[lines=10..-1]
----

==== LOGICAL_NOT

Elementwise logical NOT of input.

*Precision Requirements*

Results must be exact.

include::{generated}/operators/LOGICAL_NOT.adoc[]

[source,c++]
----
include::{pseudocode}/operators/LOGICAL_NOT.tosac[lines=10..-1]
----

==== NEGATE

Elementwise negation operation.

*Precision Requirements*

Integer Results must be exact.

For floating-point values, the following rules apply:

* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.
* Infinity, NaN, and Zero behavior as defined in the following table.
* Otherwise floating-point results must be exact.

include::{generated}/operators/NEGATE.adoc[]

*Floating-point behavior:*
|===
|Input|-infinity|+infinity|-0|+0|NaN

|Output|+infinity|-infinity|+0|-0|any NaN
|===

[source,c++]
----
include::{pseudocode}/operators/NEGATE.tosac[lines=10..-1]
----

==== RECIPROCAL

Elementwise reciprocal operation. For integer operation, a TABLE should be used with the appropriate ranges.

*Precision Requirements*

* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.
* Infinity, NaN, and Zero behave as defined in the following table.
* Otherwise, the following may be used to validate the result:
** Let `x` be an input element and `out_imp` the implementation output.
** Let `out_ref` be the result of the fp64_t reference implementation.
** Then `tosa_reference_check_fp<in_t>(out_imp, out_ref, 1)` must be true.

include::{generated}/operators/RECIPROCAL.adoc[]

*Floating-point behavior:*
|===
|Input|-infinity|+infinity|-0|+0|NaN

|Output|-0|+0|-infinity|+infinity|any NaN
|===

[source,c++]
----
include::{pseudocode}/operators/RECIPROCAL.tosac[lines=10..-1]
----

==== RSQRT

Elementwise reciprocal square root operation. For integer operation, a TABLE should be used with the appropriate ranges.

*Precision Requirements*

* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.
* Infinity, NaN, and Zero behave as defined in the following table.
* Otherwise, the following may be used to validate the result:
** Let `x` be an input element and `out_imp` the implementation output.
** Let `out_ref` be the result of the fp64_t reference implementation.
** Then `tosa_reference_check_fp<in_t>(out_imp, out_ref, 2)` must be true.

include::{generated}/operators/RSQRT.adoc[]

*Floating-point behavior:*
|===
|Input|-infinity|+infinity|-0|+0|any NaN

|Output|NaN|+0|-infinity|+infinity|any NaN
|===

[source,c++]
----
include::{pseudocode}/operators/RSQRT.tosac[lines=10..-1]
----

==== SIN

Elementwise sine operation for values given in radians.

*Precision Requirements*

* Subnormal bf16_t, fp16_t, and fp32_t input values may be flushed to zero before calculation.
* Infinity, NaN, and Zero behavior as defined in the Floating-point behavior table.
* Otherwise, the following may be used to validate the result:
** Let `x` be an input element and `out_imp` the implementation output of `sin(x)`.
** Let `out_ref` be the result of the fp64_t reference implementation of `sin(x)`.
** Let `err_bnd = max(calcAbsErrorBound<in_out_t>(x, 1, 0, 2), pi*normal_min<in_out_t>())`.
** Then `tosa_reference_check_fp_bnd<in_out_t>(out_imp, out_ref, err_bnd)` must be true.

include::{generated}/operators/SIN.adoc[]

*Floating-point behavior:*
|===
|Input|-infinity|+infinity|-0|+0|NaN

|Output|any NaN|any NaN|-0|+0|any NaN
|===

[source, c++]
----
include::{pseudocode}/operators/SIN.tosac[lines=10..-1]
----
