//
// This confidential and proprietary software may be used only as
// authorised by a licensing agreement from ARM Limited
// (C) COPYRIGHT 2020-2024 ARM Limited
// ALL RIGHTS RESERVED
// The entire notice above must be reproduced on all authorised
// copies and copies may only be made to the extent permitted
// by a licensing agreement from ARM Limited.

=== Reduction Operators

==== REDUCE_ALL

Reduce a tensor along the given axis with a logical AND operation

include::{generated}/operators/REDUCE_ALL.adoc[]

[source,c]
----
include::{pseudocode}/operators/REDUCE_ALL.tosac[lines=10..-1]
----

==== REDUCE_ANY

Reduce a tensor along the given axis with a logical OR operation

include::{generated}/operators/REDUCE_ANY.adoc[]

[source,c]
----
include::{pseudocode}/operators/REDUCE_ANY.tosac[lines=10..-1]
----

==== REDUCE_MAX

Reduce a tensor along the given axis with a maximum operation

include::{generated}/operators/REDUCE_MAX.adoc[]

[source,c]
----
include::{pseudocode}/operators/REDUCE_MAX.tosac[lines=10..-1]
----

==== REDUCE_MIN

Reduce a tensor along the given axis with a minimum operation

include::{generated}/operators/REDUCE_MIN.adoc[]

[source,c]
----
include::{pseudocode}/operators/REDUCE_MIN.tosac[lines=10..-1]
----

==== REDUCE_PRODUCT

Reduce a tensor along the given axis by computing the product of the axis.

include::{generated}/operators/REDUCE_PRODUCT.adoc[]

[source,c]
----
include::{pseudocode}/operators/REDUCE_PRODUCT.tosac[lines=10..-1]
----

==== REDUCE_SUM

Reduce a tensor along the given axis by computing the sum of the axis.

include::{generated}/operators/REDUCE_SUM.adoc[]

[source,c]
----
include::{pseudocode}/operators/REDUCE_SUM.tosac[lines=10..-1]
----
