//
// This confidential and proprietary software may be used only as
// authorised by a licensing agreement from ARM Limited
// (C) COPYRIGHT 2020-2024, 2026 ARM Limited
// ALL RIGHTS RESERVED
// The entire notice above must be reproduced on all authorised
// copies and copies may only be made to the extent permitted
// by a licensing agreement from ARM Limited.

=== Scatter/Gather Operators

==== GATHER

Generate a tensor for which each element in the output is a subtensor of the values tensor based on the indices and row_count.
The number of consecutive rows gathered for each index is specified in the optional row_count, which defaults to 1 when not supplied.
N is the number of batches, W is the number of indices in each batch.
K is the total number of rows and therefore the range of each index and C is the number of data channels for each index.
The values tensor has shape [N, K, C] and the output tensor has shape [N, W*row_count, C].

*Precision Requirements*

Integer and non-block-scaled floating-point results must be exact.

The following rules apply to block-scaled outputs.

* These rules are intended to allow casting to a higher-precision scalar type as part of the computation.
* Let `out_imp_v, out_imp_s` be the value and scale of the implementation output.
* Let `out_ref_v, out_ref_s` be the value and scale calculated using fp64_t arithmetic.
* Let `value_t = get_value_t<in_out_t>()`.
* Let `scale_t = get_scale_t<in_out_t>()`.
* Then `tosa_reference_check_scale<scale_t, value_t>(out_imp_scale, out_imp_value, out_ref_scale, out_ref_value)` must be true.

include::{generated}/operators/GATHER.adoc[]

[source,c++]
----
include::{pseudocode}/operators/GATHER.tosac[lines=10..-1]
----

==== SCATTER

The values_out tensor is set to the values_in tensor with data modified as follows: data from the input tensor is inserted at the positions specified by the indices tensor.
The number of consecutive rows scattered for each index is specified in the optional row_count, which defaults to 1 when not supplied.
N is the number of batches, W the number of indices in each batch.
K the range of each index and C the number data channels for each index.
It is not permitted to have row_count overlap output indexes or repeat the same output index within a single SCATTER operation and so each output index is written at most once.
It follows that K >= (W * row_count).
In use cases that require multiple updates to the same output position, these must be decomposed into multiple SCATTER operations.

*Precision Requirements*

Integer and non-block-scaled floating-point results must be exact.

The following rules apply to block-scaled outputs.

* These rules are intended to allow casting to a higher-precision scalar type as part of the computation.
* Let `out_imp_v, out_imp_s` be the value and scale of the implementation output.
* Let `out_ref_v, out_ref_s` be the value and scale calculated using fp64_t arithmetic.
* Let `value_t = get_value_t<in_out_t>()`.
* Let `scale_t = get_scale_t<in_out_t>()`.
* Then `tosa_reference_check_scale<scale_t, value_t>(out_imp_scale, out_imp_value, out_ref_scale, out_ref_value)` must be true.

include::{generated}/operators/SCATTER.adoc[]

[source,c++]
----
include::{pseudocode}/operators/SCATTER.tosac[lines=10..-1]
----
