//
// This confidential and proprietary software may be used only as
// authorised by a licensing agreement from ARM Limited
// (C) COPYRIGHT 2020-2024, 2026 ARM Limited
// ALL RIGHTS RESERVED
// The entire notice above must be reproduced on all authorised
// copies and copies may only be made to the extent permitted
// by a licensing agreement from ARM Limited.

=== Scatter/Gather Operators

==== GATHER

Generate a tensor for which each element in the output is a subtensor of the values tensor based on the indices.
N is the number of batches, W the number of indices in each batch, K the range of each index and C the number data channels for each index.

*Precision Requirements*

Results must be exact.

include::{generated}/operators/GATHER.adoc[]

[source,c++]
----
include::{pseudocode}/operators/GATHER.tosac[lines=10..-1]
----

==== ROW_GATHER

Generate a tensor-list which contains a data tensor and an optional scale tensor based on the input indices and row_count.
The number of consecutive rows gathered for each index is specified in row_count.
The values tensor-list must have a mandatory first element and an optional second element.
N is the number of batches, W is the number of indices in each batch.
K is the total number of rows and therefore the range of each index and C is the number of data channels for each index.

* If values contains non-block-scaled data, then, this tensor-list must contain 1 element of shape [N, K, C].
** The attribute block_size must equal BLOCK_SIZE_1.
* If values contains block-scaled data types, then, this tensor-list must contain 2 elements.
** The first element must be a tensor containing block-scaled data of shape [N, K, C] and the second element must be a tensor containing scales of shape [N, K, C / block_size].
** block_size must be chosen from enum block_size_t.

*Precision Requirements*

Results must be exact.

include::{generated}/operators/ROW_GATHER.adoc[]

[source,c++]
----
include::{pseudocode}/operators/ROW_GATHER.tosac[lines=10..-1]
----

==== SCATTER

The values_out tensor is set to the values_in tensor with data modified as follows: data from the input tensor is inserted at the positions specified by the indices tensor.
N is the number of batches, W the number of indices in each batch, K the range of each index and C the number data channels for each index.
It is not permitted to repeat the same output index within a single SCATTER operation and so each output index occurs at most once.
It follows that K >= W.
In use cases that require multiple updates to the same output position, these must be decomposed into multiple SCATTER operations.

*Precision Requirements*

Results must be exact.

include::{generated}/operators/SCATTER.adoc[]

[source,c++]
----
include::{pseudocode}/operators/SCATTER.tosac[lines=10..-1]
----
