//
// This confidential and proprietary software may be used only as
// authorised by a licensing agreement from ARM Limited
// (C) COPYRIGHT 2020-2024 ARM Limited
// ALL RIGHTS RESERVED
// The entire notice above must be reproduced on all authorised
// copies and copies may only be made to the extent permitted
// by a licensing agreement from ARM Limited.

=== Scatter/Gather Operators

==== GATHER

Generate a tensor for which each element in the output is a subtensor of the values tensor based on the indices.
N is the number of batches, W the number of indices in each batch, K the range of each index and C the number data channels for each index.

*Precision Requirements*

Results must be exact.

include::{generated}/operators/GATHER.adoc[]

[source,c++]
----
include::{pseudocode}/operators/GATHER.tosac[lines=10..-1]
----

==== SCATTER

The values_out tensor is set to the values_in tensor with data modified as follows: data from the input tensor is inserted at the positions specified by the indices tensor.
N is the number of batches, W the number of indices in each batch, K the range of each index and C the number data channels for each index.
It is not permitted to repeat the same output index within a single SCATTER operation and so each output index occurs at most once.
It follows that K >= W.
In use cases that require multiple updates to the same output position, these must be decomposed into multiple SCATTER operations.

*Precision Requirements*

Results must be exact.

include::{generated}/operators/SCATTER.adoc[]

[source,c++]
----
include::{pseudocode}/operators/SCATTER.tosac[lines=10..-1]
----
